version: 2.1
jobs:
  build_annotations:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew :annotations:assemble --no-daemon --no-build-cache --refresh-dependencies
      - store_artifacts:
          path: annotations/build/libs/annotations.jar
          destination: annotations.jar
  build_processor-java:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew :processor-java:assemble --no-daemon --no-build-cache --refresh-dependencies
      - store_artifacts:
          path: processor-java/build/libs/processor-java.jar
          destination: processor-java.jar
  test_sample-android-java:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies --no-daemon --no-build-cache --refresh-dependencies
      - run: ./gradlew :sample-android:testJavaDebugUnitTest --no-daemon --no-build-cache --refresh-dependencies
      - store_test_results:
          path: sample-android/build/test-results/testJavaDebugUnitTest
  test_sample-java:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew :sample-java:test --no-daemon --no-build-cache --refresh-dependencies
      - store_test_results:
          path: sample-java/build/test-results
  ensure_tag_allowed:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: ./.circleci/ensure_tag_allowed.sh
  release_on_github:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: ./gradlew :annotations:assemble --no-daemon --no-build-cache --refresh-dependencies
      - run: ./gradlew :processor-java:assemble --no-daemon --no-build-cache --refresh-dependencies
      - run: ./.circleci/release_github.sh
  release_on_central:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Decript GPG secret keyring
          command: openssl aes-256-cbc -md sha512 -iter 100000 -d -in secring.gpg.enc -out secring.gpg -k $GPG_SECRET_DECRIPTION_KEY
          when: always
      - run:
          name: Upload annotations to Maven Central
          command: ./gradlew :annotations:publishReleasePublicationToSonatypeRepository --no-daemon --no-build-cache --refresh-dependencies
          when: always
      - run:
          name: Upload processor-java to Maven Central
          command: ./gradlew :processor-java:publishReleasePublicationToSonatypeRepository --no-daemon --no-build-cache --refresh-dependencies
          when: always
      - run:
          name: Close and release staging repository in Nexus
          command: ./gradlew closeAndReleaseRepository
          when: always
workflows:
  test_samples:
    jobs:
      - build_annotations:
          filters:
            tags:
              ignore: /.*/
      - build_processor-java:
          filters:
            tags:
              ignore: /.*/
      - test_sample-android-java:
          requires:
            - build_annotations
            - build_processor-java
      - test_sample-java:
          requires:
            - build_annotations
            - build_processor-java
  release:
    jobs:
      - ensure_tag_allowed:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build_annotations:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - ensure_tag_allowed
      - build_processor-java:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - ensure_tag_allowed
      - test_sample-android-java:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build_annotations
            - build_processor-java
      - test_sample-java:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - build_annotations
            - build_processor-java
      - release_on_github:
          context: test-accessors_release_github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - test_sample-android-java
            - test_sample-java
      - release_on_central:
          context: test-accessors_release_mavencentral
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - test_sample-android-java
            - test_sample-java
